# Generated by Django 5.1.15 on 2026-06-11 23:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiverBuoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('river_name', models.CharField(max_length=200)),
                ('water_level_m', models.FloatField(default=0.0)),
                ('alert_level_m', models.FloatField(default=3.0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IoTSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sensor_type', models.CharField(choices=[('soil_moisture', 'Humidité sol'), ('rainfall', 'Pluviomètre'), ('temperature', 'Température'), ('humidity', 'Humidité air'), ('water_level', "Niveau d'eau")], max_length=20)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('battery_level', models.FloatField(default=100.0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcels.parcel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PestTrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('pest_count', models.PositiveIntegerField(default=0)),
                ('last_image', models.ImageField(blank=True, upload_to='pest_traps/')),
                ('ai_diagnosis', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcels.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='%', max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='iot.iotsensor')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
