# Generated by Django 5.1.15 on 2026-06-12 00:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoRaDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('device_type', models.CharField(max_length=50)),
                ('network', models.CharField(default='lorawan', max_length=20)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('firmware_version', models.CharField(default='1.0.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RainGauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('rainfall_mm_today', models.FloatField(default=0)),
                ('alert_threshold_mm', models.FloatField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='SoilStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('nitrogen', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('conductivity', models.FloatField(blank=True, null=True)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockCollar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('animal_id', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('battery_pct', models.FloatField(default=100)),
                ('is_in_geofence', models.BooleanField(default=True)),
                ('herd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collars', to='livestock.herd')),
            ],
        ),
    ]
