# Generated by Django 5.1.15 on 2026-06-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('climate', 'Alerte climatique'), ('sos', 'SOS Urgence'), ('incident', 'Incident'), ('crop', 'Santé des cultures'), ('system', 'Système')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('target_role', models.CharField(blank=True, max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_broadcast', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
