# Generated by Django 5.1.15 on 2026-06-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=200)),
                ('frequency', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(max_length=50)),
                ('is_broadcast', models.BooleanField(default=False)),
                ('broadcast_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('sos', 'SOS'), ('alert', 'Alerte'), ('voice', 'Vocal'), ('ussd', 'USSD')], max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('provider', models.CharField(default='africas_talking', max_length=50)),
                ('provider_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
