# Generated by Django 5.1.15 on 2026-06-11 23:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('sos', 'SOS Urgence'), ('fire', 'Incendie'), ('flood', 'Inondation'), ('drought', 'Sécheresse'), ('pest_attack', 'Attaque ravageurs'), ('accident', 'Accident'), ('medical', 'Urgence médicale'), ('other', 'Autre')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('acknowledged', 'Pris en charge'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='high', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('photo', models.ImageField(blank=True, upload_to='incidents/')),
                ('people_affected', models.PositiveIntegerField(default=0)),
                ('is_sos', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
