# Generated by Django 5.1.15 on 2026-06-11 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=50)),
                ('quantity_kg', models.FloatField()),
                ('quality_grade', models.CharField(default='A', max_length=20)),
                ('harvest_date', models.DateField()),
                ('blockchain_hash', models.CharField(blank=True, max_length=64)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='parcels.parcel')),
            ],
            options={
                'ordering': ['-harvest_date'],
            },
        ),
    ]
