# Generated by Django 5.1.15 on 2026-06-11 23:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(choices=[('mapping', 'Cartographie'), ('spraying', 'Pulvérisation'), ('surveillance', 'Surveillance'), ('ndvi', 'Analyse NDVI')], max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('in_flight', 'En vol'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='planned', max_length=20)),
                ('flight_path', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('coverage_area', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('altitude_m', models.FloatField(default=50.0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcels.parcel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
