# Generated by Django 5.1.15 on 2026-06-11 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CropHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.CharField(max_length=20)),
                ('soil_moisture', models.FloatField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('rainfall_mm', models.FloatField(blank=True, null=True)),
                ('ndvi_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField()),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='parcels.parcel')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
