# Generated by Django 5.1.15 on 2026-06-12 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageWhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('group_id', models.CharField(blank=True, max_length=100)),
                ('admin_phone', models.CharField(max_length=20)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('alerts_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=200)),
                ('age_months', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=100)),
                ('malnutrition_risk', models.CharField(default='low', max_length=20)),
                ('food_sources', models.JSONField(default=list)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WomenFarmerProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative', models.CharField(blank=True, max_length=200)),
                ('training_completed', models.JSONField(default=list)),
                ('hectares_managed', models.FloatField(default=0)),
                ('income_xof', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='women_programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
