# Generated by Django 5.1.15 on 2026-06-11 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Terminé'), ('paused', 'En pause')], default='active', max_length=20)),
                ('focus_crop', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentored_by', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mentor', 'mentee')},
            },
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentorship.mentorship')),
            ],
        ),
    ]
