# Generated by Django 5.1.15 on 2026-06-11 23:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('crop_type', models.CharField(choices=[('maize', 'Maïs'), ('rice', 'Riz'), ('cassava', 'Manioc'), ('cocoa', 'Cacao'), ('coffee', 'Café'), ('cotton', 'Coton'), ('groundnut', 'Arachide'), ('other', 'Autre')], max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('area_hectares', models.FloatField(default=0.0)),
                ('health_status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Bon'), ('moderate', 'Modéré'), ('poor', 'Mauvais'), ('critical', 'Critique')], default='good', max_length=20)),
                ('soil_moisture', models.FloatField(default=50.0, help_text='Pourcentage 0-100')),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('expected_harvest', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
