# Generated by Django 5.1.15 on 2026-06-12 00:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('timezone', models.CharField(default='Africa/Abidjan', max_length=50)),
                ('default_language', models.CharField(default='fr', max_length=5)),
                ('emergency_number', models.CharField(default='180', max_length=20)),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'country configs',
            },
        ),
    ]
