# Generated by Django 5.1.15 on 2026-06-11 23:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('soil_type', models.CharField(choices=[('ferralsol', 'Ferralsol (latérite)'), ('leptosol', 'Leptosol (rocheux)'), ('vertisol', 'Vertisol (argileux)'), ('cambisol', 'Cambisol'), ('fluvisol', 'Fluvisol (alluvial)'), ('arenosol', 'Arenosol (sableux)')], max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('organic_matter', models.FloatField(blank=True, help_text='%', null=True)),
                ('texture', models.CharField(blank=True, max_length=50)),
                ('suitability', models.JSONField(blank=True, default=dict)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='FAO/ISRIC', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
