# Generated by Django 5.1.15 on 2026-06-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('partner_type', models.CharField(choices=[('fao', 'FAO'), ('ngo', 'ONG'), ('government', 'Gouvernement'), ('research', 'Recherche'), ('private', 'Privé')], max_length=20)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit', models.PositiveIntegerField(default=1000)),
                ('allowed_endpoints', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
