# Generated by Django 5.1.15 on 2026-06-11 23:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('drought', 'Sécheresse'), ('flood', 'Inondation'), ('heatwave', 'Canicule'), ('storm', 'Tempête'), ('hail', 'Grêle'), ('pest', 'Ravageurs'), ('disease', 'Maladie des cultures')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('center_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('affected_area_km2', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(blank=True, help_text='°C', null=True)),
                ('rainfall_mm', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, help_text='%', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='km/h', null=True)),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('ai_confidence', models.FloatField(default=0.0, help_text='Score IA 0-1')),
                ('ai_recommendation', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('elevation_m', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='°C')),
                ('rainfall_mm', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(help_text='%')),
                ('wind_speed', models.FloatField(default=0.0, help_text='km/h')),
                ('soil_moisture', models.FloatField(blank=True, help_text='%', null=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='climate.weatherstation')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
