# Generated by Django 5.1.15 on 2026-06-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=50)),
                ('crop_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('planting_start', models.CharField(help_text='MM-DD', max_length=20)),
                ('planting_end', models.CharField(max_length=20)),
                ('harvest_start', models.CharField(max_length=20)),
                ('harvest_end', models.CharField(max_length=20)),
                ('treatments', models.JSONField(default=list)),
                ('tips', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['crop_type', 'region'],
                'unique_together': {('crop_type', 'region')},
            },
        ),
    ]
