# Generated by Django 5.1.15 on 2026-06-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action', models.CharField(max_length=50)),
                ('target_count', models.PositiveIntegerField(default=1)),
                ('points_reward', models.PositiveIntegerField(default=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
