# Generated by Django 5.1.15 on 2026-06-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='fr', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Agriculteur'), ('rescue', 'Secours'), ('admin', 'Administrateur'), ('agent', 'Agent agricole'), ('vet', 'Vétérinaire'), ('ngo', 'ONG'), ('government', 'Gouvernement')], default='farmer', max_length=20),
        ),
    ]
