# Generated by Django 5.1.15 on 2026-06-12 00:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('point_type', models.CharField(choices=[('well', 'Puits'), ('borehole', 'Forage'), ('dam', 'Barrage'), ('river', "Point d'eau fluvial"), ('pump', 'Pompe')], max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('region', models.CharField(max_length=100)),
                ('capacity_m3', models.FloatField(default=0.0)),
                ('current_level_pct', models.FloatField(default=100.0)),
                ('is_functional', models.BooleanField(default=True)),
                ('community_managed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_liters', models.PositiveIntegerField(default=50)),
                ('used_today_liters', models.PositiveIntegerField(default=0)),
                ('crop_type', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('water_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='water_resources.waterpoint')),
            ],
        ),
    ]
